const Product = [
    {
      name: "Whey Protein",
      description: "High-quality protein powder.",
      price: "₹29.99",
      category: "Protein",
      image: "https://rukminim2.flixcart.com/image/416/416/xif0q/protein-supplement/m/1/i/creatine-micronised-creatine-monohydrate-lab-tested-enhanced-original-imah7bvmkmsra2pp.jpeg?q=70&crop=false",
      orders: "https://example.com/whey-protein",
    },
    {
      name: "Wellcore Pure Micronised Creatine",
      description: "Micronized Formula For Enhanced Absorption.",
      price: "₹539",
      category: "Creatine",
      image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQrFCh5v6V22m_oYyvMN8KlSD86O_iklYah6gFRrUYDLaa7NKKPwecVzKPD6egIG_apk4eGIgtZ9AnaClrOSlq-KUxaRvSHnZf26NIFooQyGGr2hfSe3QqbTcc",
      orders: "https://www.amazon.in/Wellcore-Micronised-Monohydrate-Unflavoured-Absorption/dp/B0BX46DVXZ?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1IY8HGL5UW7M4&gQT=1",
    },
    {
      name: "MuscleBlaze Creatine Monohydrate",
      description: "Micronized Formula For Enhanced Absorption.",
      price: "₹549",
      category: "Creatine",
      image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRMgML1k0jy298MvhgEEEwfpnDTsNbObYFbXFZyucOz_ak3rhVAXVTIQhTajqvrwFDIXdUBj8QfCk-w-gRnWnXQhTtby0AQkf7yYpZ70VSbSpI5KYbB4IGEHg",
      orders: "https://www.muscleblaze.com/sv/muscleblaze-creatine-monohydrate-creamp/SP-33852?navKey=VRNT-63864&gQT=1",
    },
    {
      name: "GNC Micronized Monohydrate Creatine",
      description: "Micronized Formula For Enhanced Absorption.",
      price: "₹525",
      category: "Creatine",
      image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSMo0zhVdHmHO77eDKvekV8IJmfzvkYJydUclfoLCDNydCA430Z0jqKj137Au8FkrGstUm1bolPM-uDg1C_gRHLeb0FC6CP9jDkXorePA6FWnhL42t_gKRqfg",
      orders: "https://www.flipkart.com/gnc-micronized-monohydrate-creatine/p/itmcdd627d967c7c?pid=PSLFSZNTUF4NXPAN&lid=LSTPSLFSZNTUF4NXPANQNTWCQ&marketplace=FLIPKART&cmpid=content_protein-supplement_8965229628_gmc&gQT=1",
    },
    {
      name: "AS-IT-IS Creatine Monohydrate Powder",
      description: "Micronized Formula For Enhanced Absorption.",
      price: "₹274",
      category: "Creatine",
      image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSiqKHzd6OJkEerNXbyxfRHiDlrLY0XGp0_fBO0OjcJ_3Xz0KVDl8bCOe3diCWZwypSWlPirMGr8uvvlMC9XhZ0ODGNnNdNH_zWzmxi7zPO8T9JdbWa5JdK4A",
      orders: "https://asitisnutrition.com/products/pure-creatine-monohydrate-powder?currency=INR&gQT=1&stkn=d8433d7a529a&utm_campaign=Google%20Shopping&utm_medium=cpc&utm_source=google&variant=16756154269747",
    },
    {
        name: "Optimum Nutrition Micronised Creatine Powder - Unflavoured",
        description: "Micronized Formula For Enhanced Absorption.",
        price: "₹599",
        category: "Creatine",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSimSIIQ-1bHEIogftlz_mvtTflGMkNUj0CWuy4HKJ3XrM50IsdQDGXs13dMCJvN6P02c1BN2F3ckDL8weFCaqJau0_vS7Yery0wx4rW7PeGNXKpO7GcjeC",
        orders: "https://www.bigbasket.com/pd/40307014/optimum-nutrition-micronised-creatine-powder-unflavoured-supports-muscle-strength-power-100-g/?z=MzE0OTkyNTYxNw&utm_source=google&utm_medium=cpc&utm_campaign=Noida-Ghaziabad-PLA/&gQT=1",
      },

      {
        name: "MuscleBlaze Biozyme Performance Whey",
        description: "exclusively for fitness and muscle-building champions who want their protein supplement to be as effective as their efforts.",
        price: "₹1429",
        category: "Protein",
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ3YL68q0U3SKWf0hyHe9G9G9g1w6hx58V9ALrVQmLZgfuFjL6qeEta8cPsynpY1HtPTX7zu9vDQzXbPSVN5w0DKX-HUZz3MSHfanoAsi641B6p5yFIMB9T",
        orders: "https://www.muscleblaze.com/sv/muscleblaze-biozyme-performance-whey/SP-88093?navKey=VRNT-171425&gQT=1",
      },
      {
        name: "Premium Gold Whey Protein",
        description: "exclusively for fitness and muscle-building champions who want their protein supplement to be as effective as their efforts.",
        price: "₹2899",
        category: "Protein",
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTzPmT1xq5Wai__WWImBvmn1h5KWBeO9mPk972LgctHB3Xt2NPFHzowGoBWmZiDhlNyXNITdSBZixGemeKqxscQICoee4mRBVyQ39-hnPAHmx6Z7hU_a-8C",
        orders: "https://www.bigmusclesnutrition.com/products/premium-gold-whey-protein-1?variant=40714684792931&currency=INR&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&gQT=1",
      },
      {
        name: "GNC Pro Performance 100% Whey Protein",
        description: "Faster Recovery & Lean Muscle Gains | Informed Choice Certified",
        price: "₹4699",
        category: "Protein",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTyy7uA9elTDLKWyMXQhAkxiXFLFZqPKbBUeY9FXZUNgEnjD3qYECltsOEpw07HupHFM23VON2UPHiNnBlQIJox4M-tufqMqQYUbxv3lowe0AfNwcNf6_nI",
        orders: "https://www.guardian.in/products/gnc-pro-performance-100-whey-protein?variant=44178821906663&currency=INR&gPromoCode=FREE__MULTIVITAMIN&gQT=1",
      },
      {
        name: "MuscleTech NitroTech Whey Protein",
        description: "Faster Recovery & Lean Muscle Gains | Informed Choice Certified",
        price: "₹1499",
        category: "Protein",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTpPBtNloxPFbJRPToOBby15tFZkO9Sl0meHVzXhzGTXjHGWt2no34wYVC27ydhycCPspz4in2rw_QeGytCGG0xE5QEHj6GolwnomkrX062RWhDl57_gxXVxw",
        orders: "https://www.amazon.in/MuscleTech-Nitro-Tech-Creatine-Nutrition-Chocolate/dp/B09VT28P9Y?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1HT7OL3574FUO&gQT=1",
      },
      {
        name: "",
        description: "",
        price: "₹599",
        category: "",
        image: "",
        orders: "",
      },
    {
      name: "Fish Oil",
      description: "Omega-3 fatty acids for heart health.",
      price: "₹14.99",
      category: "Fish Oil",
      image: "https://via.placeholder.com/150",
      orders: "https://example.com/fish-oil",
    },
    {
      name: "Multivitamins",
      description: "Essential vitamins and minerals.",
      price: "₹24.99",
      category: "Vitamins",
      image: "https://via.placeholder.com/150",
      orders: "https://example.com/multivitamins",
    },
    {
      name: "Peanut Butter",
      description: "Natural and creamy peanut butter.",
      price: "₹9.99",
      category: "Peanut Butter",
      image: "https://via.placeholder.com/150",
      orders: "https://example.com/peanut-butter",
    },
  ];
  
  export default Product;
  